baizhi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/', include('userapp.urls')),
    path('courseapp/', include('courseapp.urls')),
]

courseapp/urls.py
from django.urls import path

from courseapp import views
app_name = 'courseapp'


urlpatterns = [
    path('home/', views.home, name='home'),
    # path('addArticle/', views.addArticle, name='addArticle'),
    path('add_article_logic/', views.add_article_logic, name='add_article_logic'),
    path('addCourse/', views.addCourse, name='addCourse'),
    path('modify/', views.modify, name='modify'),
    path('dele/', views.dele, name='dele'),
    path('get_course/', views.get_course, name='get_course'),
    path('addarticle/', views.add_article, name='addarticle'),
    path('get_cate/', views.get_cate, name='get_cate'),
    path('modify_logic/', views.modify_logic, name='modify_logic'),
    path('add_course_logic/', views.add_course_logic, name='add_course_logic'),
    path('python/', views.python, name='python'),
    path('pythonbase/', views.pythonbase, name='pythonbase'),
    # path('index/', views.index, name='index'),
]

userapp/urls.py
from django.urls import path

from userapp import views
app_name = 'userapp'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('getcaptcha/', views.getcaptcha, name='getcaptcha'),
    path('check_name/', views.check_name, name='check_name'),
    path('register_logic/', views.register_logic, name='register_logic'),
    path('loginout/', views.loginout, name='loginout'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_logic/', views.forget_logic, name='forget_logic'),
    path('active/', views.active, name='active'),
    # path('reactive/', views.reactive, name='reactive'),
    path('reset_pwd/', views.reset_pwd, name='reset_pwd'),
    path('reset_logic/', views.reset_logic, name='reset_logic'),
]

templates/user/forget_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-忘记密码</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
	<style>
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}"></a>
			<div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>密码找回</h1>
			</div>
			<div class="reg_form clearfix">
				<form action="">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name" onblur="check_name()">
                        <span class="error_tip" id="name_span" style="display: block"></span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email" onblur="check_email()">
						<span class="error_tip" id="email_span" style="display: block"></span>
					</li>

					<li class="reg_sub">
						<input type="button" value="提交" name="" onclick="form_pwd()">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script>
        // 校验用户名
        function check_name() {
            var name = document.getElementById("user_name").value;
            var name_span = document.getElementById("name_span");
            //用户名的规则： 用户名必须为2到10位中文名称
            var rst = /^[\u4e00-\u9fa5]{2,10}$/;
            if (rst.test(name)){
                $.ajax({
                        type: 'get',
                        data: 'name=' + $('[name="user_name"]').val(),
                        url: '{% url "userapp:check_name" %}',
                        success: function(data) {
                            console.log(data);
                            if (data==="1"){
                                $('#name_span').html('用户名存在').css('color','green');
                                return true
                            }else{
                                $('#name_span').html('用户名不存在');
                                return false
                            }
                        }
                    });
                return true
            }else{
                if(name===''){
                name_span.innerHTML = "不能为空".fontcolor("red");
                    return false
                }else{name_span.innerHTML = "用户名必须为2到10位中文名称".fontcolor("red");
                    return false
                }
            }
        }


        // 校验邮箱
        function check_email() {
            var email = document.getElementById("email").value;
            var email_span = document.getElementById("email_span");
            var rst = /^\w+@(\w+\.)+(com|cn|net)$/;
            if (rst.test(email)) {
                email_span.innerHTML = ''.fontcolor('green');
                return true
            }else{
                if (email===''){
                    email_span.innerHTML = '不能为空'.fontcolor('red');
                    return false
                }else{
                    email_span.innerHTML = '不符合邮箱规则'.fontcolor('red');
                    return false
                }
            }
        }

        function form_pwd() {
            var a = check_email();
            var b = check_name();
            console.log(a,b);
            if (a&&b){}
            $.ajax({
                type: 'get',
                url: '{% url "userapp:forget_logic" %}',
                data: $('form').serialize(),//'username=' + $('#user_name').val(),
                success: function (data) {
                    if (data.status === 0){
                        alert('邮件发送失败，请重新发送');
                    }else {
                        alert('邮件发送成功，请点击邮箱连接修改密码');
                        location.href = "{% url 'userapp:reset_pwd' %}?name=" + $('#user_name').val();
                    }
                }
            })
        }

    </script>
</body>
</html>

templates/user/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function check_name() {
            var name = document.getElementById("user_name").value;
            var name_span = document.getElementById("name_span");
            //用户名的规则： 用户名必须为2到10位中文名称
            var rst = /^[\u4e00-\u9fa5]{2,10}$/;
            if (rst.test(name)){
                $.ajax({
                    type: 'get',
                    data: 'name=' + $('[name="username"]').val(),
                    url: '{% url "userapp:check_name" %}',
                    success: function(data) {
                        if (data==='0'){
                            $('#name_span').html('用户名不存在');
                            return false
                        }else{
                            $('#name_span').html('用户名存在').css('color','green');
                             return true
                        }
                    }
                });return true
            }else{
                if(name===''){
                    name_span.innerHTML = "不能为空".fontcolor("red");
                    return false
                }else{name_span.innerHTML = "用户名必须为2到10位中文名称".fontcolor("red");
                    return false
                }
            }
        }

        function check_pwd() {
            var pwd = document.getElementById("pwd").value;
            console.log(pwd);
            var pwd_span = document.getElementById("pwd_span");
            //密码的规则： 密码必须为6到18位字母、数字或下划线
            var rst = /^\w{6,18}$/;
            if(rst.test(pwd)){
                pwd_span.innerHTML = "".fontcolor("green");
                return true
            }else{
                if (pwd===''){
                    pwd_span.innerHTML = "不能为空".fontcolor('red');
                    return false
                }else{
                    pwd_span.innerHTML = '密码必须为6到18位字母、数字或下划线'.fontcolor('red')
                    return false
                }
            }
        }
        function form_login() {
            var a = check_name();
            var booa = check_pwd();
            console.log(a);
            console.log(booa);
            if (booa && a){
                $.ajax({
                type: 'post',
                url: '{% url "userapp:login_logic" %}',
                data: $('form').serialize(),
                success: function (data) {
                    if (data.status === 0){
                        alert(data.msg);
                    }else if (data.status === 1){
                        location.href = "{% url 'courseapp:home' %}"
                    }else if(data.status === 2){
                        var rst = confirm('用户未激活是否发邮件激活');
                        if(rst){
                            $.ajax({
                                type: 'get',
                                url: '{% url "userapp:active" %}',
                                data: {'username': $('[name="username"]').val()},
                                success: function (data) {
                                    if (data.status===0){
                                        alert(data.msg)
                                    }else if (data.status===1){
                                        alert(data.msg)
                                    }else {
                                        alert(data.msg)
                                    }
                                }
                            })
                        }
                    }
                }
            })
            }else{

            }
        }
    </script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo" style="font-size: 30px;">
            <img src="{% static 'images/bz_logo.gif' %}">
            <span style="color:black;font-size: 15px;">站在时代风口，抢占人工智能</span>
        </a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">百知教育 · 课程系统</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'userapp:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" id="user_name" class="name_input" placeholder="请输入用户名" onblur="check_name()">
                        <div class="user_error" id="name_span" style="display: block"></div>
						<input type="password" name="pwd" id="pwd" class="pass_input"  placeholder="请输入密码" onblur="check_pwd()">
						<div class="pwd_error" id="pwd_span"  style="display: block"></div>
						<div class="more_input clearfix">
							<input type="checkbox" name="cookie" value="1">
							<label>记住用户名</label>
							<a href="{% url 'userapp:forget_pwd' %}">忘记密码</a>
						</div>
						<input type="button" name="" value="登录" class="input_submit" onclick="form_login()">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user/logout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bodymain.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/logout.css' %}"/>
        <script src="{% static 'js/jquery.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
        <title>百知课程后台管理系统-退出</title>
    </head>
    <body>
        <div class="login_top clearfix">
            <a href="index.html" class="login_logo" style="font-size: 30px;">
                <img src="{% static 'images/bz_logo.gif' %}">
                <span style="color:black;font-size: 15px;">站在时代风口，抢占人工智能</span>
            </a>
        </div>
        <div class="content-logout"></div>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-heart-empty glyphicon"></span> 关注我们</h4>
                            <p>最受欢迎的管理平台</p>
                            <p><a href="#" class="ic_df"> 新浪微博</a> </p>
                            <p><a href="#" class="ic_weichat"> 官方微信</a> </p>
                          </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-king"> 开发平台</span> </h4>
                            <p>加入开发平台，尊享会员福利，成为资深程序猿</p>
                            <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">我要开发</a></p>
                          </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="thumbnail">
                          <div class="caption">
                            <h4><span class="glyphicon glyphicon-phone-alt"></span> 关于我们</h4>
                            <p>欢迎反馈宝贵意见</p>
                            <p class="p_idea"><a href="http://www.baizhibest.com"  class="btn btn-default btn-lg idea">意见反馈</a></p>
                          </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 cp_info">
                        <div class="no-mp">
                            <p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
                            <p>电话：010-****888    京ICP备*******8号</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box cotainer">
        	<div class="modal modal-free" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        
					        <h4 class="modal-title" id="myModalLabel">成功退出</h4>
					      </div>
					      <div class="modal-body">
					        感谢您今天在本站花费了一些宝贵时间！
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default my-btn" data-dismiss="modal">关闭窗口</button>
					        <a href="login.html" class="btn btn-default my-btn">重新登录</a>
					      </div>
					    </div>
					  </div>
					</div>
        </div>
        <script type="text/javascript">
        	
        	$(function(){
        		
        		$(".modal-header .close").click(function(){
        			
        			$("#myModal").modal("hide");
        			
        			
        			
        			
        			
        			
        			
        			
        		});
        		
        		
        		
        		
        		
        		
        		
        	});
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        	
        </script>
    </body>
</html>

templates/user/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="js/register.js"></script>
    <script>
        // 刷新验证码
        function re_img() {
            var img = document.getElementById('cap_img');
            img.src = "{% url 'userapp:getcaptcha' %}?time=" + (new Date()).getTime();
        }
        // 校验用户名
        function check_name() {
            var name = document.getElementById("user_name").value;
            var name_span = document.getElementById("name_span");
            //用户名的规则： 用户名必须为2到10位中文名称
            var rst = /^[\u4e00-\u9fa5]{2,10}$/;
            if (rst.test(name)){
                $.ajax({
                        type: 'get',
                        data: 'name=' + $('[name="user_name"]').val(),
                        url: '{% url "userapp:check_name" %}',
                        success: function(data) {
                            console.log(data);
                            if (data==="1"){
                                $('#name_span').html('用户名已存在不可用');
                                return false
                            }else{
                                $('#name_span').html('用户名可用');
                                return true
                            }
                        }
                    });
                return true
            }else{
                if(name===''){
                    name_span.innerHTML = "不能为空".fontcolor("red");
                    return false
                }else{name_span.innerHTML = "用户名必须为2到10位中文名称".fontcolor("red");
                    return false
                }
            }
        }

        // 校验密码
        function check_pwd() {
            var pwd = document.getElementById("pwd").value;
            var pwd_span = document.getElementById("pwd_span");
            //密码的规则： 密码必须为6到18位字母、数字或下划线
            var rst = /^\w{6,18}$/;
            if(rst.test(pwd)){
                pwd_span.innerHTML = "".fontcolor("green");
                return true
            }else{
                if (pwd===''){
                    pwd_span.innerHTML = "不能为空".fontcolor('red');
                    return false
                }else{
                    pwd_span.innerHTML = '密码必须为6到18位字母、数字或下划线'.fontcolor('red')
                    return false
                }
            }
        }
        // 校验二次密码
        function check_cpwd() {
            var pwd = document.getElementById("pwd").value;
            console.log(pwd);
            var cpwd = document.getElementById("cpwd").value;
            console.log(cpwd);
            var cpwd_span = document.getElementById("cpwd_span");
            var rst = /^\w{6,18}$/;
            if (rst.test(cpwd)){
                if(pwd===cpwd){
                    cpwd_span.innerHTML = "".fontcolor('green');
                    return true
                }else{
                    cpwd_span.innerHTML = "两次密码不一致".fontcolor("red");
                    return false
                }
            }else{
                if (cpwd===''){
                    cpwd_span.innerHTML = '不能为空'.fontcolor('red');
                    return false
                }else {
                    cpwd_span.innerHTML =" 密码必须为6到18位字母、数字或下划线".fontcolor("red")
                    return false
                }
            }
        }

        // 校验邮箱
        function check_email() {
            var email = document.getElementById("email").value;
            var email_span = document.getElementById("email_span");
            var rst = /^\w+@(\w+\.)+(com|cn|net)$/;
            if (rst.test(email)) {
                email_span.innerHTML = ''.fontcolor('green');
                return true
            }else{
                if (email===''){
                    email_span.innerHTML = '不能为空'.fontcolor('red');
                    return false
                }else{
                    email_span.innerHTML = '不符合邮箱规则'.fontcolor('red');
                    return false
                }
            }
        }

        // 校验验证码
        function check_captcha() {
            var captcha = document.getElementById('captcha1').value;
            console.log(captcha);
            var captcha_span = document.getElementById('captcha_span');
            if (captcha===''){
                captcha_span.innerHTML = '不能为空';
                return false
            }else{
                captcha_span.innerHTML = '';
                return true
            }
        }
        function form_submit(){
            console.log(123);
            var allow = $('input:checked').val();
            console.log(allow);
            if (allow==='on'){
                $('#allow_span').html('');
                var name = check_name();
                var email = check_email();
                var password = check_pwd();
                var captcha = check_captcha();
                var cpwd = check_cpwd();
                console.log(name,password,email,password,captcha,cpwd);

                if(name&&email&&password&&cpwd&&allow&&captcha){
                    $.ajax({
                        type:'post',
                        url: '{% url "userapp:register_logic" %}',
                        data : $('form').serialize(),
                        success: function (data) {
                            console.log(data);
                            if (data.status === 0){
                                alert(data.msg)
                            }else{
                                alert('注册成功，等待管理员审核！');
                                location.href = "{% url 'userapp:login' %}"
                            }
                        }
                    })
               }
            }else{
                $('#allow_span').html('请勾选')
            }
        }
    </script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}"></a>
			<div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'userapp:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" >
                    {% csrf_token %}
				<ul>
					<li>

						<input type="text" name="user_name" id="user_name" placeholder="请输入真实姓名" onblur="check_name()">
						<label>用户名:</label><span class="error_tip" id="name_span" style="display: block"></span>

					</li>					
					<li>

						<input type="password" name="pwd" id="pwd" placeholder="请输入密码" onblur="check_pwd()">
						<label>密码:</label><span class="error_tip" id="pwd_span" style="display: block"></span>

					</li>
					<li>

						<input type="password" name="cpwd" id="cpwd" placeholder="请输入确认密码" onblur="check_cpwd()">
						<label>确认密码:</label><span class="error_tip" id="cpwd_span" style="display: block"></span>

					</li>
					<li>

						<input type="text" name="email" id="email" placeholder="请输入邮箱" onblur="check_email()">
						<label>邮箱:</label><span class="error_tip" id="email_span" style="display: block"></span>

					</li>
					<li>
                        <label>验证码:</label>
                        <img id="cap_img" src="{% url 'userapp:getcaptcha' %}" alt="" width="80">
                        <a href="javascript:void (0)" style="text-decoration: underline;" onclick="re_img()">看不清，换一张</a>
                          <input type="text" name="captcha" id="captcha1" style="width: 100px;" onblur="check_captcha()">
                        <span class="error_tip" id="captcha_span" style="display: block"></span>

                    </li>

					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”百知课程管理系统使用协议“</label>
						<span class="error_tip2" style="display: block" id="allow_span"></span>
					</li>
					<li class="reg_sub">
                        <input type="button" value="注 册" name="" onclick="form_submit();">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/user/reset_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>百知Python课程管理系统-重置</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="js/register.js"></script>
	<style>
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
    <script>
        function check_pwd() {
            var pwd = document.getElementById("user_pwd").value;
            var pwd_span = document.getElementById("user-pwd_sapn");
            //密码的规则： 密码必须为6到18位字母、数字或下划线
            var rst = /^\w{6,18}$/;
            if(rst.test(pwd)){
                pwd_span.innerHTML = "".fontcolor("green");
                return true
            }else{
                if (pwd===''){
                    pwd_span.innerHTML = "不能为空".fontcolor('red');
                    return false
                }else{
                    pwd_span.innerHTML = '密码必须为6到18位字母、数字或下划线'.fontcolor('red');
                    return false
                }
            }
        }
        // 校验二次密码
        function check_cpwd() {
            var pwd = document.getElementById("user_pwd").value;
            console.log(pwd);
            var cpwd = document.getElementById("confirm-pwd").value;
            console.log(cpwd);
            var cpwd_span = document.getElementById("confirm-pwd_sapn");
            var rst = /^\w{6,18}$/;
            if (rst.test(cpwd)){
                if(pwd===cpwd){
                    cpwd_span.innerHTML = "".fontcolor('green');
                    return true
                }else{
                    cpwd_span.innerHTML = "两次密码不一致".fontcolor("red");
                    return false
                }
            }else{
                if (cpwd===''){
                    cpwd_span.innerHTML = '不能为空'.fontcolor('red');
                    return false
                }else {
                    cpwd_span.innerHTML =" 密码必须为6到18位字母、数字或下划线".fontcolor("red")
                    return false
                }
            }
        }
        function form_submit() {
            boo1 = check_pwd();
            boo2 = check_cpwd();
            if (boo1&&boo2){
                $.ajax({
                    type: 'post',
                    url: '{% url 'userapp:reset_logic' %}',
                    data: $('form').serialize(),
                    success: function (data) {
                        alert(data)
                    }
                })
            }
        }
    </script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/bz_logo.gif' %}"></a>
			<div class="reg_slogan">站在时代风口 · 抢占人工智能</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>重置密码</h1>
			</div>
			<div class="reg_form clearfix">
				<form method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>输入密码:</label>
						<input type="password" name="user-pwd" id="user_pwd" onblur="check_pwd()">
                        <span id="user-pwd_sapn"></span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="confirm-pwd" id="confirm-pwd" onblur="check_cpwd()">
                        <span id="confirm-pwd_sapn"></span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="提交" name="" onclick="form_submit()">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 北京百知教育科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>